import { User, Category, SystemSetting, Report, ReportStatus } from '../types/admin';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin Principal',
    email: 'admin.principal@example.com',
    role: 'admin',
    active: true,
    createdAt: new Date('2024-01-01'),
    lastLogin: new Date('2024-03-15'),
    avatar: '/avatars/admin-1.jpg'
  },
  {
    id: '2',
    name: 'Admin Secundario',
    email: 'admin.secundario@example.com',
    role: 'admin',
    active: true,
    createdAt: new Date('2024-01-15'),
    lastLogin: new Date('2024-03-20'),
    avatar: '/avatars/admin-2.jpg'
  },
  {
    id: '3',
    name: 'Supervisor Web 1',
    email: 'supervisor1@example.com',
    role: 'supervisor',
    active: true,
    createdAt: new Date('2024-02-01'),
    lastLogin: new Date('2024-03-25'),
    avatar: '/avatars/supervisor-1.jpg'
  },
  {
    id: '4',
    name: 'Supervisor Web 2',
    email: 'supervisor2@example.com',
    role: 'supervisor',
    active: false,
    createdAt: new Date('2024-02-15'),
    lastLogin: null,
    avatar: '/avatars/supervisor-2.jpg'
  },
  {
    id: '5',
    name: 'Técnico Móvil 1',
    email: 'tecnico1@example.com',
    role: 'mobile',
    active: true,
    createdAt: new Date('2024-03-01'),
    lastLogin: new Date('2024-03-30'),
    mobileUserType: 'technician',
    avatar: '/avatars/mobile-tech-1.jpg'
  },
  {
    id: '6',
    name: 'Técnico Móvil 2',
    email: 'tecnico2@example.com',
    role: 'mobile',
    active: true,
    createdAt: new Date('2024-03-05'),
    lastLogin: new Date('2024-04-01'),
    mobileUserType: 'technician',
    avatar: '/avatars/mobile-tech-2.jpg'
  },
  {
    id: '7',
    name: 'Ciudadano 1',
    email: 'ciudadano1@example.com',
    role: 'mobile',
    active: true,
    createdAt: new Date('2024-03-10'),
    lastLogin: new Date('2024-04-05'),
    mobileUserType: 'citizen',
    avatar: '/avatars/mobile-citizen-1.jpg'
  },
  {
    id: '8',
    name: 'Ciudadano 2',
    email: 'ciudadano2@example.com',
    role: 'mobile',
    active: false,
    createdAt: new Date('2024-03-15'),
    lastLogin: null,
    mobileUserType: 'citizen',
    avatar: '/avatars/mobile-citizen-2.jpg'
  },
  {
    id: '9',
    name: 'Visualizador 1',
    email: 'viewer1@example.com',
    role: 'viewer',
    active: true,
    createdAt: new Date('2024-03-20'),
    lastLogin: new Date('2024-04-10'),
    avatar: '/avatars/viewer-1.jpg'
  },
  {
    id: '10',
    name: 'Visualizador 2',
    email: 'viewer2@example.com',
    role: 'viewer',
    active: false,
    createdAt: new Date('2024-03-25'),
    lastLogin: null,
    avatar: '/avatars/viewer-2.jpg'
  }
];

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Alumbrado Público',
    description: 'Problemas relacionados con el alumbrado público',
    color: '#FFA000',
    icon: 'lightbulb',
    active: true,
    createdAt: new Date('2024-01-01')
  },
  {
    id: 'cat-2',
    name: 'Recolección de Basura',
    description: 'Problemas relacionados con la recolección de basura',
    color: '#4CAF50',
    icon: 'trash',
    active: true,
    createdAt: new Date('2024-01-01')
  },
  {
    id: 'cat-3',
    name: 'Estado de las Calles',
    description: 'Problemas relacionados con el estado de las calles',
    color: '#F44336',
    icon: 'road',
    active: true,
    createdAt: new Date('2024-01-01')
  },
  {
    id: 'cat-4',
    name: 'Parques y Jardines',
    description: 'Problemas relacionados con parques y jardines',
    color: '#8BC34A',
    icon: 'tree',
    active: true,
    createdAt: new Date('2024-01-01')
  },
  {
    id: 'cat-5',
    name: 'Mobiliario Urbano',
    description: 'Problemas relacionados con el mobiliario urbano',
    color: '#607D8B',
    icon: 'bench',
    active: true,
    createdAt: new Date('2024-01-01')
  },
];

export const mockSettings: SystemSetting[] = [
  {
    id: 'setting-1',
    key: 'app_name',
    value: 'City Services App',
    description: 'Nombre de la aplicación',
    group: 'general'
  },
  {
    id: 'setting-2',
    key: 'contact_email',
    value: 'contact@example.com',
    description: 'Email de contacto',
    group: 'general'
  },
  {
    id: 'setting-3',
    key: 'api_url',
    value: 'https://api.example.com',
    description: 'URL de la API',
    group: 'api'
  },
  {
    id: 'setting-4',
    key: 'map_provider',
    value: 'Google Maps',
    description: 'Proveedor de mapas',
    group: 'map'
  },
];

export const mockReports: Report[] = [
  {
    id: 1,
    title: "Broken Street Light",
    category: "Infrastructure",
    status: "Open",
    priority: "Medium",
    location: "Av. Reforma 123",
    assignedTo: "Carlos Gutierrez",
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Pothole on Main Street",
    category: "Road",
    status: "In Progress",
    priority: "High",
    location: "Calle 16 de Septiembre",
    assignedTo: "Ana Mendoza",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    title: "Sample Report 3",
    category: "Infrastructure",
    status: "Open",
    priority: "Low",
    location: "Location 3",
    assignedTo: "User 3",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    title: "Sample Report 4",
    category: "Road",
    status: "In Progress",
    priority: "Medium",
    location: "Location 4",
    assignedTo: "User 4",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    title: "Sample Report 5",
    category: "Environment",
    status: "Resolved",
    priority: "High",
    location: "Location 5",
    assignedTo: "User 5",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    title: "Sample Report 6",
    category: "Public Service",
    status: "Approved",
    priority: "Medium",
    location: "Location 6",
    assignedTo: "User 6",
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 7,
    title: "Sample Report 7",
    category: "Infrastructure",
    status: "Rejected",
    priority: "Low",
    location: "Location 7",
    assignedTo: "User 7",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 8,
    title: "Sample Report 8",
    category: "Road",
    status: "Open",
    priority: "High",
    location: "Location 8",
    assignedTo: "User 8",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 9,
    title: "Sample Report 9",
    category: "Environment",
    status: "In Progress",
    priority: "Medium",
    location: "Location 9",
    assignedTo: "User 9",
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 10,
    title: "Sample Report 10",
    category: "Public Service",
    status: "Resolved",
    priority: "Low",
    location: "Location 10",
    assignedTo: "User 10",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 11,
    title: "Sample Report 11",
    category: "Infrastructure",
    status: "Approved",
    priority: "High",
    location: "Location 11",
    assignedTo: "User 11",
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 12,
    title: "Sample Report 12",
    category: "Road",
    status: "Rejected",
    priority: "Medium",
    location: "Location 12",
    assignedTo: "User 12",
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 13,
    title: "Sample Report 13",
    category: "Environment",
    status: "Open",
    priority: "Low",
    location: "Location 13",
    assignedTo: "User 13",
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 14,
    title: "Sample Report 14",
    category: "Public Service",
    status: "In Progress",
    priority: "High",
    location: "Location 14",
    assignedTo: "User 14",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 15,
    title: "Sample Report 15",
    category: "Infrastructure",
    status: "Resolved",
    priority: "Medium",
    location: "Location 15",
    assignedTo: "User 15",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 16,
    title: "Sample Report 16",
    category: "Road",
    status: "Approved",
    priority: "Low",
    location: "Location 16",
    assignedTo: "User 16",
    createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 17,
    title: "Sample Report 17",
    category: "Environment",
    status: "Rejected",
    priority: "High",
    location: "Location 17",
    assignedTo: "User 17",
    createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 18,
    title: "Sample Report 18",
    category: "Public Service",
    status: "Open",
    priority: "Medium",
    location: "Location 18",
    assignedTo: "User 18",
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
